### PR TITLE
#6 Branding Changes

### LINKED ISSUE #6: Improve the documentation format to align with the branding standard
1. Design color schema for all bundle attributes based on the latest branding standard
2. Update the text fonts based on the latest branding standard.
3. Remove the 'root' top header with 'bundle name' + Documentation
4. Add latest branding logo at the top of the documentation with proper size
5. change \ to / for attribute path

### PR DESCRIPTION
**Pull request by championshuttler**
Fixes #6 
Title contains -> MACHINE LEARNING DOCUMENTATION with a Logo on the right
For Links we used blue3 -> #0000AF
For Other Fonts we used standard black color -> black

### CODE REVIEW

**Comment by lilyclemson** [comment]
Please update the type and sizes of font for the documentation based on the latest branding standard.

**Comment by lilyclemson** [comment]
Merged

**Comment by lilyclemson** [comment]
Please resolve the merge conflicts with mainSub branch.

**Comment by championshuttler** [comment]
Done @lilyclemson

**Comment by lilyclemson** [comment]
Merged to mainSub

**Pull request merged**
